### ISSUE TITLE
About the train/dev/eval protocols for FMFCC-A database

### ISSUE THREAD

**Issue by TonyWangX** [Amforever/FMFCC-A#1]
Dear author,

Thank your very much for the work on FMFCC-A database! Very useful to the community.

I've downloaded the database following the link on baidupan. After unrar the file, I noticed that there are wave files and a FMFCC-AdatasetLabel.txt file (filename, 0/1)

Do you consider releasing the protocols for the training, development, eval sets? 

Thank you!

**Comment by Amforever** [comment]
Oh, sorry.  In fact, we put all the WAV files in one folder as the FMFCC-A dataset. If you want to do train/dev/eval version like in the  Challenge, 20000001.wav to 20010001.wav are utterances in training data set for the FMFCC, 20010001.wav to 20030000.wav  are in dev set, and 20030001.wav to 20050000.wav are in eval set.  I hope this explanation can help you.

**Comment by TonyWangX** [comment]
Got it. Thank you!.
