### ISSUE TITLE
数据集细节缺失

### ISSUE THREAD

**Issue by petrichorwq** [Amforever/FMFCC-A#2]
Dear author，

Thanks for your works in FMFCC-A dataset constructing.

However,  I found that details (eg. spoof algorithm, post-processing) corresponding to each audio file are not marked.

I wonder if it is possible for you to publish more details about the dataset？

Thank you~

**Comment by Amforever** [comment]
Thanks for your appreciation on our  work, we will relased the detailed label file including  spoof algorithm and post-processing of each utterance in the next few days.

**Comment by petrichorwq** [comment]
Thank you！
