### ISSUE TITLE
Dataset details information

### ISSUE THREAD

**Issue by ZigHello** [Amforever/FMFCC-A#3]
Dear Author:
Is it possible to provide the forged category tag message for the audio?
Best wishes to you！

**Comment by Amforever** [comment]
Hello, the forged category of each utterance is described as the third column in "AllUtteranceInfo.txt". The detailed information speech synthetic methods are presented in  the paper "FMFCC-A: AChallenging Mandarin Dataset for Synthetic Speech Detection
".
Hope the answer can help  you, if you have any questions, please contact us.

**Comment by ZigHello** [comment]
oh～thank you！It was my carelessness that left out the third column.
