### ISSUE TITLE
speaker tag

### ISSUE THREAD

**Issue by hello-xiaow** [Amforever/FMFCC-A#4]
Dear author,

Thank your very much for the work on FMFCC-A database! Very useful to the community.

Could you provide the speaker tag like the tag file of asvspoof2019？

Thank you!

**Comment by Amforever** [comment]
Sorry for that. We thought that the fake speech detection aims to distinguish real speech from fake speech which should not consider the specific speaker. Therefore, the labels of the speakers were not provided.

**Comment by hello-xiaow** [comment]
Okay, thank you！
